language: go

go:
  - 1.6
  - 1.5.3
install:
  - go get golang.org/x/net/websocket
  - go get github.com/go-sql-driver/mysql
  - go get github.com/golang/protobuf/proto
after_script:
  -killall -w ssdb-server
  - rm -rf ./res/var/*
script:
  - go test -v ./...
