#!/bin/bash
#
# cfgsd        Startup script for log server.
#
# chkconfig: 345 90 4

# Source function library.
. /etc/init.d/functions

export LD_LIBRARY_PATH=/usr/local/lib
RETVAL=0
SRV_HOME=RV_SRVD_HOME
SRV_D=$SRV_HOME
pro_n=cfgs
srv_n=$pro_n"d"
usr_n=$srv_n
addr=:9700
token=conf/token.properties
PIDFILE=/var/run/$srv_n.pid
lockfile=/var/lock/$srv_n.lock
exec=$SRV_D/$pro_n
start() {
	[ -x $exec ] || exit 5

	umask 077

        echo -n "Starting $srv_n server: "
        daemonize -o /var/log/$srv_n/out.log -e /var/log/$srv_n/err.log -c $SRV_D -p $PIDFILE -u $usr_n -l $lockfile $exec $addr $token $SRV_HOME
        RETVAL=$?
	echo
        [ $RETVAL -eq 0 ] && touch $lockfile
	return $RETVAL
}
stop() {
        echo -n "Shutting down $srv_n server: "
        killproc -p "$PIDFILE" $exec
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $lockfile
        return $RETVAL
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
esac

exit $?
