// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	ImMsg
	RC
	DsMsg
	KV
	Evn
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ImMsg struct {
	I                *string  `protobuf:"bytes,1,opt,name=i" json:"i,omitempty" bson:"_id"`
	S                *string  `protobuf:"bytes,2,opt,name=s" json:"s,omitempty"`
	R                []string `protobuf:"bytes,3,rep,name=r" json:"r,omitempty"`
	T                *uint32  `protobuf:"varint,4,req,name=t" json:"t,omitempty"`
	D                *string  `protobuf:"bytes,5,opt,name=d" json:"d,omitempty"`
	C                []byte   `protobuf:"bytes,6,req,name=c" json:"c,omitempty"`
	A                *string  `protobuf:"bytes,7,opt,name=a" json:"a,omitempty"`
	Time             *int64   `protobuf:"varint,8,opt,name=time" json:"time,omitempty"`
	Status           *string  `protobuf:"bytes,9,opt,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ImMsg) Reset()                    { *m = ImMsg{} }
func (m *ImMsg) String() string            { return proto.CompactTextString(m) }
func (*ImMsg) ProtoMessage()               {}
func (*ImMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ImMsg) GetI() string {
	if m != nil && m.I != nil {
		return *m.I
	}
	return ""
}

func (m *ImMsg) GetS() string {
	if m != nil && m.S != nil {
		return *m.S
	}
	return ""
}

func (m *ImMsg) GetR() []string {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *ImMsg) GetT() uint32 {
	if m != nil && m.T != nil {
		return *m.T
	}
	return 0
}

func (m *ImMsg) GetD() string {
	if m != nil && m.D != nil {
		return *m.D
	}
	return ""
}

func (m *ImMsg) GetC() []byte {
	if m != nil {
		return m.C
	}
	return nil
}

func (m *ImMsg) GetA() string {
	if m != nil && m.A != nil {
		return *m.A
	}
	return ""
}

func (m *ImMsg) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *ImMsg) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

type RC struct {
	R                *string `protobuf:"bytes,1,req,name=r" json:"r,omitempty"`
	C                *string `protobuf:"bytes,2,req,name=c" json:"c,omitempty"`
	A                *string `protobuf:"bytes,3,req,name=a" json:"a,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RC) Reset()                    { *m = RC{} }
func (m *RC) String() string            { return proto.CompactTextString(m) }
func (*RC) ProtoMessage()               {}
func (*RC) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RC) GetR() string {
	if m != nil && m.R != nil {
		return *m.R
	}
	return ""
}

func (m *RC) GetC() string {
	if m != nil && m.C != nil {
		return *m.C
	}
	return ""
}

func (m *RC) GetA() string {
	if m != nil && m.A != nil {
		return *m.A
	}
	return ""
}

type DsMsg struct {
	M                *ImMsg `protobuf:"bytes,1,req,name=m" json:"m,omitempty"`
	Rc               []*RC  `protobuf:"bytes,2,rep,name=rc" json:"rc,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DsMsg) Reset()                    { *m = DsMsg{} }
func (m *DsMsg) String() string            { return proto.CompactTextString(m) }
func (*DsMsg) ProtoMessage()               {}
func (*DsMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DsMsg) GetM() *ImMsg {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *DsMsg) GetRc() []*RC {
	if m != nil {
		return m.Rc
	}
	return nil
}

type KV struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Val              *string `protobuf:"bytes,2,req,name=val" json:"val,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *KV) Reset()                    { *m = KV{} }
func (m *KV) String() string            { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()               {}
func (*KV) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *KV) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *KV) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

type Evn struct {
	Uid              *string `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Action           *string `protobuf:"bytes,3,req,name=action" json:"action,omitempty"`
	Time             *int64  `protobuf:"varint,4,req,name=time" json:"time,omitempty"`
	Type             *int32  `protobuf:"varint,5,req,name=type" json:"type,omitempty"`
	Kvs              []*KV   `protobuf:"bytes,6,rep,name=kvs" json:"kvs,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Evn) Reset()                    { *m = Evn{} }
func (m *Evn) String() string            { return proto.CompactTextString(m) }
func (*Evn) ProtoMessage()               {}
func (*Evn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Evn) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *Evn) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Evn) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func (m *Evn) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Evn) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *Evn) GetKvs() []*KV {
	if m != nil {
		return m.Kvs
	}
	return nil
}

func init() {
	proto.RegisterType((*ImMsg)(nil), "ImMsg")
	proto.RegisterType((*RC)(nil), "RC")
	proto.RegisterType((*DsMsg)(nil), "DsMsg")
	proto.RegisterType((*KV)(nil), "KV")
	proto.RegisterType((*Evn)(nil), "Evn")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x3c, 0x8f, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0xc7, 0x15, 0xbb, 0x09, 0xe4, 0x5a, 0x3e, 0x9a, 0x05, 0x4f, 0x28, 0xb2, 0x84, 0x14, 0x09,
	0xc9, 0x03, 0x8f, 0x40, 0x61, 0x40, 0x15, 0x4b, 0x87, 0x0e, 0x0c, 0x48, 0x6e, 0x1a, 0x22, 0x03,
	0x4e, 0x22, 0xdb, 0x0d, 0xca, 0xdb, 0x73, 0x8e, 0x93, 0x6e, 0xbf, 0x3b, 0x9f, 0xff, 0x1f, 0x90,
	0x6a, 0x5b, 0x8b, 0xce, 0xb4, 0xae, 0xe5, 0x06, 0xe2, 0x37, 0xfd, 0x6e, 0xeb, 0x2c, 0x85, 0x48,
	0xb1, 0x28, 0x8f, 0x8a, 0xd4, 0xa3, 0x65, 0x64, 0x46, 0xc3, 0x68, 0x4e, 0x03, 0x3a, 0xb6, 0xc8,
	0x49, 0x71, 0xe5, 0xf1, 0xc8, 0xe2, 0xf9, 0xa0, 0x64, 0x09, 0x6e, 0x57, 0x1e, 0x25, 0xbb, 0x18,
	0xb7, 0x2b, 0x58, 0x38, 0xa5, 0x2b, 0x76, 0x89, 0x13, 0xcd, 0xae, 0x21, 0xb1, 0x4e, 0xba, 0x93,
	0x65, 0xa9, 0x7f, 0xe5, 0x0f, 0x40, 0x76, 0x9b, 0x20, 0x1d, 0xe1, 0xcf, 0x49, 0x84, 0xcc, 0x28,
	0xd1, 0x10, 0x91, 0x3f, 0x42, 0xfc, 0x62, 0x7d, 0xb4, 0x35, 0x44, 0x7a, 0xbc, 0x5c, 0x3e, 0x25,
	0x22, 0xa4, 0xbd, 0x01, 0x62, 0xfc, 0x17, 0x8a, 0x3b, 0x2a, 0x76, 0x1b, 0x7e, 0x0f, 0x64, 0xbb,
	0xcf, 0x96, 0x40, 0x7f, 0xaa, 0x61, 0x52, 0xc5, 0xa1, 0x97, 0xbf, 0x41, 0x97, 0x7f, 0x02, 0x7d,
	0xed, 0x1b, 0xbf, 0x3b, 0xa9, 0xe3, 0x74, 0x80, 0x29, 0x1b, 0x89, 0x29, 0x83, 0x33, 0xa6, 0x94,
	0xa5, 0x53, 0x6d, 0x13, 0xec, 0xcf, 0x1d, 0x7c, 0x65, 0x3a, 0x4e, 0x43, 0x57, 0x61, 0x6b, 0x52,
	0xc4, 0xd9, 0x2d, 0xfa, 0xf4, 0x16, 0x7b, 0x07, 0xff, 0xed, 0xfe, 0xf9, 0x0e, 0xd6, 0xad, 0xa9,
	0x45, 0xd9, 0x0c, 0xe2, 0xfb, 0xef, 0x4b, 0x28, 0x2d, 0xba, 0xc3, 0x07, 0xe9, 0x0e, 0xff, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x76, 0xe2, 0x68, 0x55, 0x6c, 0x01, 0x00, 0x00,
}
