// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	ImMsg
	RC
	DsMsg
*/
package pb

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ImMsg struct {
	I                *string  `protobuf:"bytes,1,opt,name=i" json:"i,omitempty"`
	S                *string  `protobuf:"bytes,2,opt,name=s" json:"s,omitempty"`
	R                []string `protobuf:"bytes,3,rep,name=r" json:"r,omitempty"`
	T                *uint32  `protobuf:"varint,4,req,name=t" json:"t,omitempty"`
	D                *string  `protobuf:"bytes,5,opt,name=d" json:"d,omitempty"`
	C                []byte   `protobuf:"bytes,6,req,name=c" json:"c,omitempty"`
	Time             *int64   `protobuf:"varint,7,opt,name=time" json:"time,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ImMsg) Reset()         { *m = ImMsg{} }
func (m *ImMsg) String() string { return proto.CompactTextString(m) }
func (*ImMsg) ProtoMessage()    {}

func (m *ImMsg) GetI() string {
	if m != nil && m.I != nil {
		return *m.I
	}
	return ""
}

func (m *ImMsg) GetS() string {
	if m != nil && m.S != nil {
		return *m.S
	}
	return ""
}

func (m *ImMsg) GetR() []string {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *ImMsg) GetT() uint32 {
	if m != nil && m.T != nil {
		return *m.T
	}
	return 0
}

func (m *ImMsg) GetD() string {
	if m != nil && m.D != nil {
		return *m.D
	}
	return ""
}

func (m *ImMsg) GetC() []byte {
	if m != nil {
		return m.C
	}
	return nil
}

func (m *ImMsg) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

type RC struct {
	R                *string `protobuf:"bytes,1,req,name=r" json:"r,omitempty"`
	C                *string `protobuf:"bytes,2,req,name=c" json:"c,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RC) Reset()         { *m = RC{} }
func (m *RC) String() string { return proto.CompactTextString(m) }
func (*RC) ProtoMessage()    {}

func (m *RC) GetR() string {
	if m != nil && m.R != nil {
		return *m.R
	}
	return ""
}

func (m *RC) GetC() string {
	if m != nil && m.C != nil {
		return *m.C
	}
	return ""
}

type DsMsg struct {
	M                *ImMsg `protobuf:"bytes,1,req,name=m" json:"m,omitempty"`
	Rc               []*RC  `protobuf:"bytes,2,rep,name=rc" json:"rc,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DsMsg) Reset()         { *m = DsMsg{} }
func (m *DsMsg) String() string { return proto.CompactTextString(m) }
func (*DsMsg) ProtoMessage()    {}

func (m *DsMsg) GetM() *ImMsg {
	if m != nil {
		return m.M
	}
	return nil
}

func (m *DsMsg) GetRc() []*RC {
	if m != nil {
		return m.Rc
	}
	return nil
}

func init() {
}
